name: Copy Packages to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  LIBRARY_JSON: libraries.json
  PYTHON_VERSION: "3.8"
  S3_BUCKET_NAME: "YOUR_BUCKET_NAME"
  TFE_DIR: layers

jobs:
  configure:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./${{ env.LIBRARY_JSON }})" >> $GITHUB_OUTPUT

  create-lambda-layer-zip:
    runs-on: ubuntu-20.04
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Check matrix values
        run: |
          echo ${{ matrix.name }}
          echo ${{ matrix.version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Extract Name and Version
        run: |
          echo "LIBRARY_NAME=${{ matrix.name }}" >> $GITHUB_ENV
          echo "LIBRARY_VERSION=${{ matrix.version }}" >> $GITHUB_ENV
          echo "ZIP_NAME=${{ matrix.name }}-${{ matrix.version }}.zip" >> $GITHUB_ENV

      - name: Install Python Library and Zip
        run: |
          mkdir -p ${{ env.TFE_DIR }}/python
          pip3 install "${LIBRARY_NAME}==${LIBRARY_VERSION}" -t ${{ env.TFE_DIR }}/python
          zip -r $ZIP_NAME ${{ env.TFE_DIR }}/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./$ZIP_NAME s3://${{ env.S3_BUCKET_NAME }}/"$ZIP_NAME"